title: "Broadcast spells"
hero_image: images/banner.png
description: Use a magic wand to choose spells and broadcast spell messages to turn sprites into toads and grow and shrink them.
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Choose your wand
  - title: The shrink spell
  - title: The grow spell
  - title: Toad transformation
  - title: Add another character
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
  - title: What next?
